<script lang="ts">
	import { renderSVG } from 'uqr';
	import ChevronLeft from 'lucide-svelte/icons/chevron-left';
	import { Breadcrumb, BreadcrumbItem, Button, Label, Field } from '$lib/components/base/index.js';
	import { PageContent, PageHeader } from '$lib/components/page/index.js';
	import { getToastState } from '$lib/states/index.js';
	import { superForm } from 'sveltekit-superforms/client';

	let { data } = $props();
	const qr = renderSVG(data.keyURI);

	const toastState = getToastState();
	const { form, errors, enhance } = superForm(data.form, {
		onResult: ({ result }) => {
			if (result.type != 'failure') return;
			if (result.data == null || result.data.form.errors._errors == null) return;
			toastState.error(result.data.form.errors._errors);
		}
	});
</script>

<svelte:head>
	<title>2fa Setup - Stackbold</title>
</svelte:head>
<PageHeader>
	<Button theme="secondary" variant="icon" class="lg:hidden" onclick={() => history.back()}>
		<ChevronLeft />
	</Button>
	<Breadcrumb class="hidden lg:flex">
		<BreadcrumbItem icon="settings" name="Settings" link="/settings" />
		<BreadcrumbItem icon="security" name="Setup two-factor authentication" last />
	</Breadcrumb>
</PageHeader>

<PageContent class="lg:justify-center items-center">
	<h1 class="form-title">Two-factor authentication</h1>

	<p class="text-center font-semibold">Scan the QR code into your app.</p>
	<div class="size-64 mb-6">
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		{@html qr}
	</div>

	<p class="text-center font-semibold">Enter the authentication code generated by your app.</p>
	<form method="post" use:enhance class="form-container">
		<input name="key" value={data.encodedTOTPKey} hidden required />
		<Field class="py-1" errors={$errors.code}>
			<Label for="code" name="Code" />
			<input
				id="code"
				type="text"
				name="code"
				required
				bind:value={$form.code}
				class="input input-ghost"
			/>
		</Field>
		<Button type="submit" class="w-full">Save</Button>
	</form>
</PageContent>
